export const categs = [
  "Material Specimens",
  "Text",
  "(not assigned)",
  "Jewelry",
  "Paintings",
  "Plaques",
  "Medals and Medallions",
  "Mosaics",
  "Mirrors",
  "Inscriptions",
  "Performance Artifacts",
  "Drawings",
  "Sculpture",
  "Tools and Equipment",
  "Textile Arts",
  "Unidentified",
  "Fragments",
  "Ritual Implements",
  "Stained Glass",
  "Brick Stamps",
  "Furnishings",
  "Gems",
  "Accessories (non-art)",
  "Multiples",
  "Vessels",
  "Paintings with Calligraphy",
  "Boxes",
  "Portfolios",
  "Amulets",
  "Armor",
  "Riding Equipment",
  "Tablets",
  "Straus Materials",
  "Artists' Materials",
  "Tokens",
  "Audiovisual Works",
  "Artists' Tools",
  "Timepieces",
  "Weapons and Ammunition",
  "Manuscripts",
  "Seals",
  "Recreational Artifacts",
  "Musical Instruments",
  "Measuring Devices",
  "Albums",
  "Cameos",
  "Graphic Design",
  "Rubbings",
  "Photographs",
  "Prints",
  "Lighting Devices",
  "Books",
  "Coins",
  "Archival Material",
  "Calligraphy",
  "Furniture",
  "Architectural Elements",
];
