export const periods = [
  "Heian period, 794-1185",
  "Kamakura period, Late or Nambokuchō",
  "Old Syrian period",
  "Tang dynasty to Northern Song period",
  "Safavid period and Zand period",
  "Minoan period, Middle",
  "Suk'otai Period",
  "Minoan period, Late Minoan II",
  "Ayudhya period, 1350-1757",
  "Late Period, Dynasty 27",
  "Xindian culture, c. 1600-600 BCE",
  "Helladic period, Middle Helladic II",
  "Helladic period, Late Helladic III",
  "Zangid period",
  "Old Kingdom, Dynasty 5",
  "Chalcolithic period",
  "Almohad period",
  "Neolithic period, Late",
  "Minoan period, Middle Minoan IB",
  "Lower Xiajiadian culture, c. 2000-1500 BCE",
  "Neolithic period, Dawenkou culture, c. 4300-2600 BCE",
  "Helladic period, Middle",
  "Zand period to early Qajar period",
  "Minoan period, Late Minoan IA",
  "Helladic period, Late Helladic IIB",
  "Neolithic period, Majiayao culture, c. 3300-2000 BCE",
  "Aq Qoyunlu period",
  "Nara period, 710-794",
  "Queen Anne (1702-1714)",
  "First Intermediate Period",
  "George IV (1820-1830)",
  "Byzantine period, Late",
  "Artuqids of Mardin period",
  "Artuqids of Kayfa and Amid period",
  "Taishō to Shōwa period",
  "New Kingdom, Dynasty 18, Amarna period",
  "Three Kingdoms period, 220-280 CE",
  "Cypro-Archaic period",
  "Tang dynasty, 618-907",
  "Byzantine period",
  "Umayyad period",
  "Classical period, Late",
  "Roman Imperial period",
  "Momoyama period, 1568-1615",
  "Ming dynasty, 1368-1644",
  "Hellenistic period to Early Roman Imperial",
  "Classical period",
  "Neolithic period, Longshan culture, c. 3000-1900 BCE",
  "Heian period, Late, 898-1185",
  "Minoan period",
  "Neo-Assyrian period",
  "George I (1714-1727)",
  "Meroitic period",
  "Roman Republican period, Late, to Early Imperial",
  "Neolithic period to Shang dynasty",
  "Three Kingdoms period, Kaya, 42 BCE-562 CE",
  "Unified Silla to Koryŏ dynasty",
  "Neo-Sumerian period, Third Dynasty of Ur",
  "Middle Kingdom",
  "Old Kingdom",
  "Nambokuchō (1333-1392) to Muromachi (1392-1568) period",
  "Hellenistic period, Late, to Early Roman Imperial",
  "Jalayirid period",
  "Seljuk-Atabeg period",
  "Licchavi (5th-9th century) to Thakuri (9th-12th century) dynasty",
  "Pallava Dynasty, 4th-9th centuries",
  "Iron Age II",
  "Shang dynasty,  c. 1600-c. 1050 BCE",
  "Zhou dynasty, Eastern Zhou period, 770-256 BCE",
  "Warring States to Western Han period",
  "Jin to Yuan dynasty",
  "New Kingdom, Dynasty 20",
  "Minoan period, Early Minoan II",
  "Late Period, Dynasty 30, to Ptolemaic",
  "Helladic period, Late",
  "Minoan period, Early Minoan I",
  "Minoan period, Early Minoan III",
  "Tang dynasty to Five Dynasties period",
  "Liao to Jin dynasty",
  "Neolithic period, Songze culture, c. 3900-3300 BCE",
  "Shōwa period, 1926-1989",
  "Prehistoric",
  "Crusader period",
  "Meiji, Taishō or early Shōwa period",
  "Late Period, Dynasty 25",
  "Middle Ages, High",
  "Yuan to Ming dynasty",
  "Qing dynasty to Modern period",
  "Minoan period, Middle Minoan IA",
  "Marinid period",
  "Aghlabid period",
  "Protogeometric period",
  "Northern and Southern Dynasties period to Sui dynasty",
  "Taishō or early Shōwa period",
  "Idrisid period",
  "Minoan period, Middle Minoan III",
  "Helladic period, Late Helladic IIIC",
  "Assyrian Colony period",
  "Sui to Tang dynasty",
  "Taishō period, 1912-1926",

  "Neo-Babylonian period",
  "Tulunid period",
  "Seleucid period",
  "Siba culture, c. 2000-1600 BCE",
  "Tumulus Period, 250-552",
  "Taishō to Shōwa period, 20th century",
  "Meiji, Taishō or Shōwa period",
  "Helladic period, Early Helladic III",
  "Edo period, 1615-1868",
  "Neolithic period",
  "Hellenistic period",
  "Hittite Empire period",
  "Geometric period, Late",
  "Yuan dynasty, 1279-1368",
  "Han dynasty, Western Han period, 206 BCE-9 CE",
  "Ottoman period",
  "Abbasid period",
  "Classical period, Late, to Hellenistic",
  "Akkadian period",
  "Jemdet Nasr period",
  "Three Kingdoms period, Paekche, 18 BCE-660 CE",
  "Sabaean period",
  "Taishō to Shōwa period, early 20th century",
  "Archaic period to Classical",
  "Classical period to Hellenistic",
  "Early Dynastic III period",
  "Geometric period to Classical",
  "Erlitou culture, c. 1900-1500 BCE",
  "Zhou dynasty, c. 1050-221 BCE",
  "Three Kingdoms period, Silla or Kaya",
  "Eastern Wei to Northern Qi",
  "Northern Qi to Sui dynasty",
  "Muromachi (1392-1568) to Edo (1615-1868) period",
  "Nara period, Early, 645-710",
  "Minoan period, Late Minoan IB",
  "Chosŏn dynasty to Modern period",
  "Northern and Southern Dynasties period, 420-589",
  "Shaybanid period",
  "New Kingdom",
  "Minoan period, Late Minoan IIIB",
  "Helladic period, Middle Helladic I",
  "Ghurid period",
  "Helladic period",
  "James II (1685-1688)",
  "Jin dynasty, Western Jin period, 266-317",
  "Xixia kingdom, 1032-1227",
  "Asuka period, 552-645",
  "Heian period, Early, 794-898",
  "Seljuks of Rum period",
  "Neolithic period, Shijiahe culture",
  "Kofun period, 250-600",
  "Zhou dynasty, Warring States period, 475-221 BCE",
  "Kamakura period, 1185-1333",
  "Hellenistic period, Early",
  "Qing dynasty, 1644-1911",
  "Classical period, High",
  "Classical period, Late, to Early Hellenistic",
  "Koryŏ dynasty, 918-1392",
  "George III (1760-1820)",
  "Roman period",
  "Roman Republican period",
  "Roman Imperial period, Late",
  "Song dynasty, Northern Song period, 960-1127",
  "Parthian period",
  "Three Kingdoms period, Silla, 57 BCE-668 CE",
  "Neolithic period, Liangzhu culture, c. 3300-2200 BCE",
  "Late Period",
  "Achaemenid period",
  "Mitannian period",
  "Timurid period",
  "Dvaravati Period",
  "Sultanate period",
  "Late Period, Dynasty 26",
  "Orientalizing period",
  "Karakota period, c. 7th-9th centuries",
  "Byzantine period, Middle",
  "Iron Age III",
  "Protogeometric period to Geometric",
  "Northern Qi, 550-577",
  "Sa'did period",
  "Geometric period, Middle",
  "Almoravid period",
  "Predynastic period",
  "Early Dynastic period",
  "Five Dynasties period to Northern Song period",
  "Neolithic period, Qujialing culture, c. 3000-2500 BCE",
  "Muromachi period, Late or Momoyama period",
  "Afsharid period",
  "Middle Kingdom, Dynasty 12",
  "Cycladic period",
  "Old Kingdom, Dynasty 4",
  "Iron Age IV",
  "Six Dynasties period, 220-589",
  "Koryŏ to Chosŏn dynasty",
  "William and Mary (1688-1702)",
  "Muzaffarid period",
  "New Kingdom to Third Intermediate Period",
  "Qara Qoyunlu period",
  "Helladic period, Late Helladic IIIA",
  "Helladic period, Late Helladic IIA",
  "Jin dynasty, 266-420",
  "Mamluk period",
  "Minoan period, Late Minoan IIIC",
  "Southern Song period to Yuan dynasty",
  "Momoyama (1568-1615) to Edo (1615-1868) period",
  "Zand period",
  "Third Intermediate Period, Dynasty 22",
  "Three Kingdoms period, Koguryŏ, 37 BCE-668 CE",
  "Ubaid period",
  "Hafsid period",
  "Pala dynasty, 760-1142",
  "Ghaznavid period",
  "Roman Imperial period, Early",
  "Song dynasty, Southern Song period, 1127-1279",
  "Fatimid period",
  "Angkor period, 802-1431",
  "Mughal period",
  "Jin dynasty, 1115-1234",
  "Minoan period, Late",
  "George II (1727-1760)",
  "Han dynasty, 206 BCE-220 CE",
  "Unified Silla dynasty, 668-935",
  "Byzantine period, Early",
  "Heisei period, 1989-2019",
  "Kushan period, c.100 BCE-250 CE",
  "Commonwealth & Protectorate (1649-1660)",
  "Roman Imperial period, Late, to Early Byzantine",
  "Shang dynasty to Western Zhou period",
  "Old Kingdom, Dynasty 6",
  "Neolithic period, Hongshan culture, c. 4500-3000 BCE",
  "Old Babylonian/Isin-Larsa period",
  "Ptolemaic period to Roman Imperial",
  "Cypro-Geometric period",
  "Orientalizing period to Archaic",
  "Geometric period to Orientalizing",
  "Third Intermediate Period",
  "Late Period to Roman",
  "Middle Ages",
  "Northern Wei or Eastern Wei, 386-550",
  "Northern Song to Jin period",
  "Neolithic period, Yangshao culture, c. 5000-3000 BCE",
  "Jin dynasty, Eastern Jin period, 317-420",
  "Jōmon period, c. 10,500-c. 400 BCE",
  "Jōmon period, Middle, c. 2500-c. 1500 BCE",
  "Qin dynasty, 221-206 BCE",
  "Helladic period, Late Helladic I",
  "Neolithic period, Peiligang culture, c. 6500-5000 BCE",
  "Turkman period",
  "Liao dynasty, 907-1125",
  "Muromachi (1392-1568) to Momoyama (1568-1615) period",
  "British period",
  "Taishō or Shōwa period",
  "Edo period, Late to early Meiji period",
  "Predynastic period to Old Kingdom",
  "Minoan period, Late Minoan IIIA",
  "Five Dynasties period to Song dynasty",
  "Ming to Qing dynasty",
  "Neolithic period, Shandong Longshan culture, c. 2600-2000 BCE",
  "Charles I (1625-1649)",
  "Minoan period, Middle Minoan II",
  "Helladic period, Late Helladic IIIB",
  "'Alawid period",
  "Song dynasty, 960-1279",
  "Five Dynasties period, 907-960",
  "Geometric period, Early",
  "Meiji period, 1868-1912",
  "Cycladic period, Late",
  "Ayyubid period",
  "Uruk period",
  "Inju period, 1303-1357",
  "Pre-Angkor period",
  "New Kingdom, Dynasty 19",
  "Qijia culture, c. 2300-1500 BCE",
  "Siwa culture, c. 1300-500 BCE",
  "Hellenistic period, Late",
  "Iron Age",
  "Chosŏn dynasty, 1392-1910",
  "Zhou dynasty, Spring and Autumn period, 770-476 BCE",
  "Roman Imperial period, Middle",
  "Hellenistic period, Middle",
  "Classical period, Early",
  "Bronze Age, Middle",
  "Archaic period",
  "Muromachi period, 1392-1568",
  "Bronze Age, Early",
  "Bronze Age",
  "Sasanian period",
  "Archaic period, Late, to Early Classical",
  "Ptolemaic period",
  "Bronze Age, Late",
  "Late Antique period",
  "Cycladic period, Early",
  "Islamic period",
  "Han dynasty, Eastern Han period, 25-220 CE",
  "Safavid period",
  "Sui dynasty, 581-618",
  "Ilkhanid period",
  "Nambokuchō period, 1333-1392",
  "Charles II (1660-1685)",
  "Samanid period",
  "Cola period, c. 9th-13th centuries",
  "Qajar period",
  "New Kingdom, Dynasty 18",
  "Geometric period",
  "Archaic period to Hellenistic",
  "Modern",
  "Late Period to Ptolemaic",
  "Iron Age II-III",
  "Middle Ages, Early",
  "Zhou dynasty, Western Zhou period, c. 1050-771 BCE",
  "Eastern Han to Three Kingdoms period",
  "Northern Wei, 386-534",
  "Eastern Wei, 534-550",
];
