export const technique = [
  "Spongotype",
  "Electroplated",
  "Cerograph",
  "Qingbai",
  "Stipple engraving and roulette",
  "Etching, aquatint and roulette",
  "Silver-dye bleach print",
  "Drypoint and aquatint",
  "Aquatint and drypoint",
  "Felt",
  "Resist dyed",
  "Woodburytype",
  "Punch'ong",
  "Photoetching, aquatint and embossing",
  "Negative, mixed technique",
  "Relief metal cut",
  "Pile weave",
  "Reverse painting on glass",
  "Etching and lithograph",
  "Engraving and stipple engraving",
  "Heliogravure",
  "White ware",
  "Glypotograph",
  "Laser print",
  "Etching and engraving",
  "Electrotype",
  "Dye diffusion transfer print",
  "Photoetching",
  "Photoengraving",
  "Metal cut",
  "Scratchwork",
  "Flocking",
  "Engraving",
  "Albumen silver print",
  "Etching",
  "Gelatin silver print",
  "Mezzotint",
  "Platinum print",
  "Wheel-made",
  "Positive photostat print",
  "Underglazed, painted",
  "Jasperware",
  "Embossed",
  "Mold-made",
  "Typewriting",
  "Daguerreotype",
  "Stamped",
  "Woven, tapestry weave",
  "Glazed-monochrome",
  "Lusterware",
  "Negative, color",
  "Stucco",
  "Letterpress and relief halftone",
  "Redware",
  "Relief halftone",
  "Autochrome",
  "Mold-blown glass",
  "Grisaille",
  "Etching, softground etching and drypoint",
  "Photogravure and etching",
  "Cuerda seca",
  "Gelatin dry plate (glass)",
  "Free-blown glass",
  "Tintype",
  "Carbon print",
  "Negative print",
  "Zincograph",
  "Illuminated",
  "Brocade",
  "Woodcut and screen print",
  "Kuftgari",
  "Screen print and collage",
  "Cloisonné",
  "Negative, gelatin silver (paper)",
  "Spitbite etching",
  "Rubber stamp",
  "Marbled",
  "Positive 4 x 5 transparency",
  "Stencil print",
  "Unglazed",
  "Wash manner",
  "Woodcut and lithography",
  "SX-70 Polaroid print",
  "Photogravure and drypoint",
  "Intaglio print",
  "Polaroid transfer print",
  "Shino",
  "Engraving and drypoint",
  "Engraving and softground etching",
  "Tin glaze",
  "Gum dichromate print",
  "Underglazed, sgraffiato",
  "Intaglio print and planographic",
  "Cutout",
  "Aquatint and stipple engraving",
  "Engraving and etching",
  "Etching and chiaroscuro woodcut",
  "Slide, 35 mm, color",
  "Lithograph",
  "Relief",
  "Slide, 35 mm, black and white",
  "Cast",
  "Etching and aquatint",
  "Cibachrome (TM)",
  "Relief print",
  "Tapestry",
  "Chiaroscuro woodcut",
  "Etching and drypoint",
  "Cast, lost-wax process",
  "Negative photostat print",
  "Fresco painting",
  "Woven with pile",
  "Knotted",
  "Painted",
  "Iris digital print",
  "Woven, twill",
  "Heliotype",
  "Inkless engraving",
  "Positive Vandyke print",
  "Drypoint, softground etching and aquatint",
  "Photolithograph, collagraph, and chine collée",
  "Mimeograph",
  "Red-figure",
  "Core-formed glass",
  "Wax resist",
  "Ambrotype",
  "photolithograph and screen print",
  "Needlepoint",
  "Etching, aquatint and photoetching",
  "Filigree",
  "Nature print",
  "Cliché-verre",
  "Collotype and stencil",
  "Ilfachrome",
  "Pastel manner",
  "Physionotrace",
  "Collagraph",
  "Brushwork",
  "Wood engraving and screen print",
  "Die cut",
  "Tabby (textile)",
  "Woodblock print",
  "Ormolu",
  "Etching and photoetching",
  "Pierced",
  "Aquatint and lithograph",
  "Photo offset lithograph",
  "Black-brown glaze",
  "Assemblage",
  "Engraving and letterpress",
  "Duotone offset photolithograph",
  "Softground etching and aquatint",
  "Transparency",
  "Woven, weft-faced plain weave",
  "Laqabi",
  "Polacolor ER",
  "White ground",
  "Wood engraving",
  "Stipple engraving",
  "Engraving and aquatint",
  "Stipple engraving and etching",
  "Lacquered",
  "Cut",
  "Negative, gelatin dry plate (glass)",
  "Blue-and-white ware",
  "Screen print",
  "Jun",
  "Linocut",
  "Photolithograph",
  "Photogravure",
  "Negative, glass plate",
  "Engraved",
  "Collodion process",
  "Repoussé",
  "Chromogenic print",
  "Monotype",
  "Cyanotype",
  "Crayon manner print",
  "Photographic reproduction",
  "Relief etching",
  "Hammered",
  "Lead glaze",
  "Etching, engraving and drypoint",
  "Blueprint",
  "Hectograph",
  "Pigment print",
  "3.5 x 4.5 Polaroid print",
  "Barbotine",
  "Halftone print",
  "Offset print",
  "Black-figure",
  "Struck",
  "Bromoil print",
  "Screen print and photograph",
  "Marquetry",
  "Relief cut",
  "Lithograph and screen print",
  "Salt glaze",
  "Gypsograph",
  "Etching, aquatint and lithograph",
  "Baxter process",
  "Mina’i",
  "Electrophotograph",
  "Dye destruction print",
  "Aquatint and mezzotint",
  "Etching and stipple",
  "Velvet",
  "Etching, softground etching and aquatint",
  "Softground etching, mezzotint, and aquatint",
  "Lace",
  "Bizen",
  "Softground etching, aquatint and woodcut",
  "LightJet (TM)",
  "Embroidery",
  "Aquatint and roulette",
  "Etching and softground etching",
  "Linocut and screen print",
  "Ink jet digital print",
  "Rubbing",
  "Gum bichromate print",
  "Verifax matrix print",
  "Mixed technique",
  "Pochoir",
  "Etching, drypoint and aquatint",
  "Black glaze",
  "Palladium print",
  "Ikat",
  "Appliqué",
  "Gillotage",
  "Carborundum print",
  "Sgraffito",
  "Negative, gelatin silver (film)",
  "Photomechanical print",
  "Etching and mezzotint",
  "Celadon",
  "Collage",
  "Carved",
  "Salted paper print",
  "Glazed",
  "Negative, gelatin silver (35mm film)",
  "Woven",
  "Handmade",
  "Photoscreenprint",
  "Counterproof",
  "20 x 24 Polaroid print",
  "Negative Vandyke print",
  "Polychromed",
  "White-ground",
  "Impressed",
  "Overglazed",
  "Photogram",
  "Cast, sand",
  "Softground etching",
  "Etching and woodcut",
  "Woven, soumak",
  "Wood engraving and letterpress",
  "Enamelled",
  "Etching and stipple engraving",
  "Intaglio print and screen print",
  "Burnished",
  "Typewriting and rubber stamp",
  "Satin",
  "Softground etching and aquatint and etching",
  "Basaltes ware",
  "Etching, stipple engraving and roulette",
  "Etching and roulette",
  "Seto",
  "Compound weave",
  "Fresson print",
  "Niello",
  "Ziatype",
  "Monoprint",
  "Pressed",
  "Softground etching and mezzotint",
  "Maiolica",
  "Pâte sur pâte",
  "Majolica (industrial)",
  "Roulette",
  "Duogravure",
  "Holograph",
  "Aquatint and softground etching",
  "Chased",
  "Stipple",
  "Collotype, stencil and cutout",
  "Digital image",
  "8 x 10 Polaroid print",
  "Chromolithograph",
  "Diazotype",
  "Woodcut",
  "Photocopy",
  "Molded",
  "Collotype",
  "Incised",
  "Drypoint",
  "Aquatint",
  "Intaglio",
  "Underglazed",
  "Gilded",
  "Lost-wax process",
  "Dye transfer print",
  "Xerograph",
  "Lampas",
  "Inlaid",
  "Overglaze enamel",
  "Woodcut and letterpress",
  "Photograph",
  "Letterpress",
  "Woven, mixed technique",
  "Champlevé",
  "Matte collodion print",
  "Line block",
  "Transfer drawing",
  "Gel-lithograph",
  "Cast and hammered",
];
